CREATE TABLE EMPLOYEE(
   EMP_ID   INT           NOT NULL,
   NAME VARCHAR (20)     NOT NULL,
   PRIMARY KEY (EMP_ID)
);

CREATE TABLE TEAMDETAILS(
   TEAM_ID INT    NOT NULL,
   EMP_ID  INT    NOT NULL REFERENCES EMPLOYEE(EMP_ID),
   SUB_ID  INT ,
   SUP_ID  INT    NOT NULL
);

CREATE TABLE REIMBURSEMENT_FORM_DETAILS(
   FORM_ID   		INT     NOT NULL,
   SUBMITTER_ID  	INT     NOT NULL REFERENCES EMPLOYEE(EMP_ID),
   APPROVER_ID 		INT	NOT NULL REFERENCES EMPLOYEE(EMP_ID),
   TYPE		   VARCHAR(30)  NOT NULL,
   RECEIPT_NUM		INT	NOT NULL,  
   AMOUNT	   FLOAT        NOT NULL,
   TO_DATE	   TIMESTAMP	NOT NULL,
   FROM_DATE	   TIMESTAMP	NOT NULL,
   STATUS	   VARCHAR(20)	NOT NULL,
   MODIFIED_DATE   TIMESTAMP	NOT NULL,
   CERT_TYPE	   VARCHAR(30),
   IS_PASS	   VARCHAR(1),
   SCORE	   FLOAT,
   ACTIVITY_TYPE   VARCHAR(30),
   TRAINING_TYPE   VARCHAR(30),
   FROM_COUNTRY    VARCHAR(30),
   FROM_CITY       VARCHAR(30),
   TO_COUNTRY      VARCHAR(30),
   TO_CITY         VARCHAR(30),   
   PRIMARY KEY (FORM_ID)
);



